apiVersion: v1
kind: Namespace
metadata:
  name: mas-devops
  labels:
    security.openshift.io/scc.podSecurityLabelSync: 'false'
    openshift.io/run-level: '0'    
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged  
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mas-devops-service-account
  namespace: mas-devops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mas-devops-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: mas-devops-service-account
    namespace: mas-devops
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mas-devops-app
  name: mas-devops-app
  namespace: mas-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mas-devops-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mas-devops-app
    spec:
      serviceAccountName: mas-devops-service-account
      containers:
      - name: main
        imagePullPolicy: Always
        image: quay.io/ibmmas/cli:latest
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        securityContext:
           runAsUser: 0
